global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nestJS'
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'server-resource'
    static_configs:
      - targets: ['host.docker.internal:9100']
